%import common.INT -> INT
%import common.CNAME -> ID
%import common.ESCAPED_STRING -> STRING
%import common.WS

%ignore WS

?start: expr
    
?expr: seq
     | "replace" strcat strcat "with" strcat -> repl

?seq: assign ";" seq -> seq
    | assign 

?assign: ID ":=" ifexpr -> assign
       | ifexpr

?ifexpr: "if" expr "then" expr "else" expr -> if_
       | logic_or

?logic_or: logic_or "||" logic_and -> lor
         | logic_and

?logic_and: logic_and "&&" logic_not -> land
          | logic_not

?logic_not: "!" logic_not -> lnot
          | compare

?compare: strcat "==" strcat -> equal
        | strcat "<" strcat -> less
        | strcat

?strcat: strcat "++" add -> concat
       | add 

?add: add "+" mul -> plus
    | add "-" mul -> minus
    | mul

?mul: mul "*" unary -> times
    | mul "/" unary -> divide
    | unary

?unary: "-" unary -> neg
      | atom

?atom: ID -> id
     | INT -> int
     | STRING -> string
     | "(" expr ")"
     | "let" ID "=" expr "in" expr "end" -> let
     | "letfun" ID "(" ID ")" "=" expr "in" expr "end" -> letfun
     | atom "(" expr ")" -> app