from interp import Add, Sub, Mul, Div, Neg, And, Or, Not, Let, Letfun, App, Name, Lit, Eq, Lt, If, Expr, run

from lark import Lark, Token, ParseTree, Transformer
from lark.exceptions import VisitError
from pathlib import Path

VERBOSE = False
# VERBOSE = True    # uncomment for verbose output

# parser = Lark(Path('expr.lark').read_text(),start='expr',parser='earley',ambiguity='explicit')
parser = Lark(Path('expr.lark').read_text(),start='expr', parser='lalr',strict=True) # uncommon for unambiguous check

class ParseError(Exception):
    pass

def parse(s:str) -> ParseTree:
    try:
        return parser.parse(s)
    except Exception as e:
        raise ParseError(e)
    
class AmbiguousParse(Exception):
    pass

class ToExpr(Transformer[Token,Expr]):
    '''Defines a transformation from a parse tree into an AST'''
    # This is structured as a "fold" over the parse tree.
    # There is a method for each named ("aliased") rule in the grammar,
    # invoked on nodes generated by that rule. 
    # The args are the _result_ of recursively 
    # applying the transformer to the children of the node
    # (we do not have to write the recursive calls explicitly).
    # For leaf nodes, the argument is a Token; the string that
    # actually makes up the token is in the .value field.
    # (We cheat by declaring the args as tuples rather than lists, since
    # this let's us be more precise about the types of the elements.)
    # Fail if tree contains ambiguity markers
    def plus(self, args:tuple[Expr,Expr]) -> Expr:
        return Add(args[0],args[1])
    def minus(self, args:tuple[Expr,Expr]) -> Expr:
        return Sub(args[0],args[1])
    def times(self, args:tuple[Expr,Expr]) -> Expr:
        return Mul(args[0],args[1])
    def divide(self, args:tuple[Expr,Expr]) -> Expr:
        return Div(args[0],args[1])
    def neg(self, args:tuple[Expr]) -> Expr:
        return Neg(args[0])  
    def logic_or(self,args:tuple[Expr,Expr]) -> Expr:
        return Or(args[0],args[1])
    def logic_and(self,args:tuple[Expr,Expr]) -> Expr:
        return And(args[0],args[1])
    def logic_not(self,args:tuple[Expr]) -> Expr:
        return Not(args[0])
    def let(self, args:tuple[Token,Expr,Expr]) -> Expr:
        return Let(args[0].value,args[1],args[2])
    def id(self, args:tuple[Token]) -> Expr:
        match args[0].value:
            case "true":
                return Lit(True)
            case "false":
                return Lit(False)
            case n:
                return Name(n)
    def int(self,args:tuple[Token]) -> Expr:
        return Lit(int(args[0].value))
    def equal(self,args:tuple[Expr,Expr]) -> Expr:
        return Eq(args[0],args[1])
    def less(self,args:tuple[Expr,Expr]) -> Expr:
        return Lt(args[0],args[1])
    def letfun(self,args:tuple[Token,Token,Expr,Expr]) -> Expr:
        return Letfun(args[0].value,args[1].value,args[2],args[3])
    def app(self,args:tuple[Expr,Expr]) -> Expr:
        return App(args[0],args[1])   
    def if_(self,args:tuple[Expr,Expr,Expr]) -> Expr:
        return If(args[0],args[1],args[2])
    def _ambig(self,_) -> Expr:
        raise AmbiguousParse()
    
def genAST(t:ParseTree) -> Expr:
    '''Applies the transformer to convert a parse tree into an AST'''
    # boilerplate to catch potential ambiguity error raised by transformer
    try:
        return ToExpr().transform(t)               
    except VisitError as e:
        if isinstance(e.orig_exc,AmbiguousParse):
            raise AmbiguousParse()
        else:
            raise e
        
def driver():
    while True:
        try:
            s = input('expr: ')
            t = parse(s)
            print("raw:", t)    
            print("pretty:")
            print(t.pretty())
            ast = genAST(t)
            print("raw AST:", repr(ast))  # use repr() to avoid str() pretty-printing
            run(ast)                      # pretty-prints and executes the AST
        except AmbiguousParse:
            print("ambiguous parse")                
        except ParseError as e:
            print("parse error:")
            print(e)
        except EOFError:
            break

def parse_and_run(s:str) -> None:
    try:
        t = parse(s)
        if VERBOSE:
            print("raw:", t)    
            print("pretty:")
            print(t.pretty())
        ast = genAST(t)
        if VERBOSE:
            print("raw AST:", repr(ast))  # use repr() to avoid str() pretty-printing
        run(ast)                      # pretty-prints and executes the AST
    except AmbiguousParse:
        print("ambiguous parse")                
    except ParseError as e:
        print("parse error:")
        print(e)

def main():
    # arithmetic
    parse_and_run("1 + 2")
    parse_and_run("let x = 2 in x * 3 end")
    parse_and_run("let x = 10 in let y = 2 in x / y end end")
    parse_and_run("-(3 + 4)")

    # boolean
    parse_and_run("true && false")
    parse_and_run("!true || false")
    parse_and_run("!(true && false)")

    # comparisons and conditionals
    parse_and_run("1 == 1")
    parse_and_run("1 < 2")
    parse_and_run("if 1 == 1 then 1 else 0")
    parse_and_run("if 1 < 2 then true else false")

    # functions
    parse_and_run("letfun double(x) = x * 2 in double(5) end")
    parse_and_run("letfun fact(n) = if n == 0 then 1 else n * fact(n - 1) in fact(5) end")

    # error cases
    parse_and_run("1 + true")       # EvalError: addition of non-integers
    parse_and_run("1 / 0")          # EvalError: division by zero

if __name__ == "__main__":
    main()